steps:
  - id: Build dockerfile
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/${PROJECT_ID}/gleich.dev:${BRANCH_NAME}
      - --file=build/Dockerfile
      - .
images:
  - gcr.io/${PROJECT_ID}/gleich.dev:${BRANCH_NAME}