name: ci

on:
  push:

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.1'

      - name: Build
        run: hugo --minify

      - name: Deploy to Netlify (dev)
        uses: nwtgck/actions-netlify@v2.0.0
        id: netlify
        with:
          publish-dir: './public'
          production-deploy: false
          github-deployment-environment: 'dev'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          fails-without-credentials: true
        timeout-minutes: 1

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@8.0.0
        with:
          urls: |
            ${{ steps.netlify.outputs.deploy-url }}
            ${{ steps.netlify.outputs.deploy-url }}/certificates/
            ${{ steps.netlify.outputs.deploy-url }}/article/golangs-omitempty/
          budgetPath: ./.github/lighthouse/budget.json
          uploadArtifacts: true

      - name: Deploy to Netlify (prod)
        if: github.ref == 'refs/heads/master'
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: './public'
          production-deploy: true
          github-deployment-environment: 'prod'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          fails-without-credentials: true
        timeout-minutes: 1
